#pragma once

struct DrawSegmentStruct;

std::vector<DrawSegmentStruct> mysupercoolandawesomeparsingfunctionthathasnoissuesorflawswhatsoeverthesearethepositiveaffirmationsitellmyselfinthemirror(GJGameLevel* level);